# Generated by Django 5.0.1 on 2024-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='display_products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='home_prods', verbose_name='Imagen'),
        ),
    ]
