# Generated by Django 5.0.1 on 2024-01-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='display_products',
            name='benefit',
            field=models.ManyToManyField(to='home.benefits', verbose_name='Beneficios'),
        ),
        migrations.AddField(
            model_name='indications',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icono'),
        ),
    ]
